# Anubistoken <anubistoken.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCM2FMAXYCXM2LTI2VABS4YLD3YQGBU3T5FCHDAAMQWL2SPNDBKQBEF3"
]

[DOCUMENTATION]
ORG_NAME="Anubistoken"
ORG_URL="https://stellarzoom.github.io/"
ORG_LOGO = "https://stellarzoom.github.io/img/anubis.png"
ORG_OFFICIAL_EMAIL="non"
ORG_SUPPORT_EMAIL="non"
ORG_TWITTER="0xanubistoken"
ORG_DESCRIPTION="Anubistoken: Create Value to Meme Coin Space"

[[PRINCIPALS]]
email="non"

[[CURRENCIES]]
code = "1BOSS"
name = "1BOSS"
issuer = "GCM2FMAXYCXM2LTI2VABS4YLD3YQGBU3T5FCHDAAMQWL2SPNDBKQBEF3"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of 1BOSS."
image="https://stellarzoom.github.io/img/anubis.png"
conditions="There will only ever be 1 billion 1BOSS tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
