# Anubistoken <anubistoken.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCM2FMAXYCXM2LTI2VABS4YLD3YQGBU3T5FCHDAAMQWL2SPNDBKQBEF3","GCKUR4FJUOZKVS6M3SLUZTECFG5Y5UQHX2JLIQYXZWNLQBLUQPP6XQT3"
]

[DOCUMENTATION]
ORG_NAME="STELLARREWORD"
ORG_URL="https://stellarreword.github.io/"
ORG_LOGO ="https://stellarreword.github.io/img/crown.png"
ORG_OFFICIAL_EMAIL="stellarreword@proton.me"
ORG_SUPPORT_EMAIL="stellarreword@proton.me"
ORG_DESCRIPTION=": Create Value to Meme Coin Space"

[[PRINCIPALS]]
email="non"

[[CURRENCIES]]
code ="1BOSS"
name ="1BOSS"
issuer = "GCM2FMAXYCXM2LTI2VABS4YLD3YQGBU3T5FCHDAAMQWL2SPNDBKQBEF3"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarreword.github.io/img/crown.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000


[[CURRENCIES]]
code ="SGB"
name ="SWEES GOLD BOND"
issuer = "GCM2FMAXYCXM2LTI2VABS4YLD3YQGBU3T5FCHDAAMQWL2SPNDBKQBEF3"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarreword.github.io/img/SGB.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="BTC"
name ="THIS IS KING"
issuer = "GCM2FMAXYCXM2LTI2VABS4YLD3YQGBU3T5FCHDAAMQWL2SPNDBKQBEF3"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarreword.github.io/img/BTC.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code ="Kay"
name ="KAKER KAY"
issuer = "GCM2FMAXYCXM2LTI2VABS4YLD3YQGBU3T5FCHDAAMQWL2SPNDBKQBEF3"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of ."
image="https://stellarreword.github.io/img/Kay.png"
conditions="There will only ever be 1 billion  tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000

[[CURRENCIES]]
code="CHATGPT"
name="ChatGPT"
issuer="GCKUR4FJUOZKVS6M3SLUZTECFG5Y5UQHX2JLIQYXZWNLQBLUQPP6XQT3"
is_asset_anchored=true
anchor_asset_type="other"
anchor_asset="ChatGPT"
image="https://stellarreword.github.io/img/chat.png"
status="live"
